#!/bin/sh
# Переходим в корень репозитория (из .git/hooks)
cd "$(dirname "$0")/../.."
FILE_PATH="src/main/resources/db/changelog/db.changelog-master.yaml"
if git merge-base --is-ancestor "$2" "$1"; then
  LAST_LINE=$(grep 'file:' "$FILE_PATH" | tail -n 1)
  VERSION=$(echo "$LAST_LINE" | sed 's/^.*db\.changelog-\(.*\)\.yml/\1/')
  if [ -n "$VERSION" ]; then
    echo "$VERSION"
  else
    echo "Версия не найдена"
  fi
fi
exit 0
